version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432" 
